// Lista de equipos para el Mundial 2026 (puedes ajustar los nombres)
const teams = [
  "Alemania",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Australia",
  "Bélgica",
  "Bosnia y Herzegovina",
  "Brasil",
  "Cabo Verde",
  "Canadá",
  "Colombia",
  "Corea del Sur",
  "Costa de Marfil",
  "Croacia",
  "Curazao",
  "Dinamarca",
  "Ecuador",
  "Egipto",
  "Emiratos Árabes Unidos",
  "Escocia",
  "España",
  "Estados Unidos",
  "Francia",
  "Ghana",
  "Haití",
  "Inglaterra",
  "Irak",
  "Irán",
  "Japón",
  "Jordania",
  "Marruecos",
  "México",
  "Noruega",
  "Nueva Zelanda",
  "Países Bajos",
  "Panamá",
  "Paraguay",
  "Portugal",
  "Qatar",
  "República Checa",
  "Congo Democrática",
  "Senegal",
  "Suecia",
  "Suiza",
  "Tunez",
  "Turquía",
  "Uruguay",
  "Uzbekistán",
];

export default teams;
